import { randomSecret, createScryptVerifier, verifyScrypt, sha256 } from "./security-crypto.js";
import { TOKEN_TTL_SECONDS, type ExternalScope, MAX_CREDENTIALS } from "./free-access-contract.js";
type Credential = { id: string; applicationId: string; clientId: string; verifier: string; scopes: ExternalScope[]; revokedAt?: number };
type Token = { hash: string; applicationId: string; scopes: ExternalScope[]; expiresAt: number; revokedAt?: number };
export function createApiClientAuth() { const credentials = new Map<string, Credential>(); const tokens = new Map<string, Token>(); return {
  createCredential(applicationId: string, scopes: ExternalScope[]) { if ([...credentials.values()].filter(c => c.applicationId === applicationId && !c.revokedAt).length >= MAX_CREDENTIALS) return undefined; const clientId = `mp_${randomSecret(12)}`; const clientSecret = randomSecret(32); credentials.set(clientId, { id: randomSecret(12), applicationId, clientId, verifier: createScryptVerifier(clientSecret), scopes }); return { clientId, clientSecret, scopes }; },
  issueToken(clientId: string, clientSecret: string, scopeText?: string) { const c = credentials.get(clientId); if (!c || c.revokedAt || !verifyScrypt(clientSecret, c.verifier)) return undefined; const requested = scopeText?.split(" ").filter(Boolean) as ExternalScope[] | undefined; const scopes = requested?.every(x => c.scopes.includes(x)) ? requested : c.scopes; const token = randomSecret(32); tokens.set(sha256(token), { hash: sha256(token), applicationId: c.applicationId, scopes, expiresAt: Date.now() + TOKEN_TTL_SECONDS * 1000 }); return { access_token: token, token_type: "Bearer", expires_in: TOKEN_TTL_SECONDS, scope: scopes.join(" ") }; },
  authenticate(token: string) { const t = tokens.get(sha256(token)); if (!t || t.revokedAt || t.expiresAt <= Date.now()) return undefined; return t; }, revokeCredential(clientId: string) { const c = credentials.get(clientId); if (c) c.revokedAt = Date.now(); }, revokeToken(token: string) { const t = tokens.get(sha256(token)); if (t) t.revokedAt = Date.now(); }, credentials };
}
