import { randomSecret, createScryptVerifier, verifyScrypt, sha256 } from "./security-crypto.js";
import { TOKEN_TTL_SECONDS, type ExternalScope, MAX_CREDENTIALS, isPublicScope, requestedScopes } from "./free-access-contract.js";
export type Credential = { id: string; applicationId: string; clientId: string; verifier: string; scopes: ExternalScope[]; revokedAt?: number };
export type Token = { hash: string; applicationId: string; scopes: ExternalScope[]; expiresAt: number; revokedAt?: number };
export type ApiClientStore = { credentials: Map<string, Credential>; tokens: Map<string, Token> };
export function createApiClientAuth(store: ApiClientStore = { credentials: new Map(), tokens: new Map() }) { return {
  createCredential(applicationId: string, scopes: ExternalScope[]) { if (scopes.length === 0 || scopes.some(s => !isPublicScope(s))) return undefined; if ([...store.credentials.values()].filter(c => c.applicationId === applicationId && !c.revokedAt).length >= MAX_CREDENTIALS) return undefined; const clientId = `mp_${randomSecret(12)}`; const clientSecret = randomSecret(32); store.credentials.set(clientId, { id: randomSecret(12), applicationId, clientId, verifier: createScryptVerifier(clientSecret), scopes: [...scopes] }); return { clientId, clientSecret, scopes: [...scopes] }; },
  issueToken(clientId: string, clientSecret: string, scopeText?: unknown) { const c = store.credentials.get(clientId); if (!c || c.revokedAt || !verifyScrypt(clientSecret, c.verifier)) return undefined; const requested = requestedScopes(scopeText); if (requested && (requested.length === 0 || requested.some(s => !c.scopes.includes(s)))) return undefined; const scopes = requested ?? c.scopes; const token = randomSecret(32); store.tokens.set(sha256(token), { hash: sha256(token), applicationId: c.applicationId, scopes, expiresAt: Date.now() + TOKEN_TTL_SECONDS * 1000 }); return { access_token: token, token_type: "Bearer", expires_in: TOKEN_TTL_SECONDS, scope: scopes.join(" ") }; },
  authenticate(token: string) { const t = store.tokens.get(sha256(token)); if (!t || t.revokedAt || t.expiresAt <= Date.now()) return undefined; return t; },
  revokeCredential(clientId: string) { const c = store.credentials.get(clientId); if (c) { c.revokedAt = Date.now(); for (const t of store.tokens.values()) if (t.applicationId === c.applicationId) t.revokedAt = Date.now(); } },
  revokeApplication(applicationId: string) { for (const c of store.credentials.values()) if (c.applicationId === applicationId) { c.revokedAt = Date.now(); for (const t of store.tokens.values()) if (t.applicationId === applicationId) t.revokedAt = Date.now(); } },
  revokeToken(token: string) { const t = store.tokens.get(sha256(token)); if (t) t.revokedAt = Date.now(); }, store
}; }
