import test from "node:test";
import assert from "node:assert/strict";
import { createApiRateLimiter } from "./api-rate-limit.js";
import { redactAuditEvent } from "./security-audit.js";
import Fastify from "fastify";
import { registerSecurityRoutes, createTestSecurityDependencies } from "./security-routes.js";
test("rate limiter fails closed at concurrency bound", () => { const limiter = createApiRateLimiter({ max: 1, maxConcurrent: 1 }); assert.equal(limiter.begin("x"), true); assert.equal(limiter.begin("x"), false); limiter.end("x"); });
test("audit output redacts credential material", () => { const value = redactAuditEvent({ event:"x", success:true, metadata:{ clientSecret:"do-not-store", nested:{ signature:"hidden" } } }); assert.equal((value.metadata as any).clientSecret, "[REDACTED]"); assert.equal((value.metadata as any).nested.signature, "[REDACTED]"); });
test("unavailable production security stores fail closed with 503", async () => { const app = Fastify(); registerSecurityRoutes(app, { available: false } as any); const response = await app.inject({ method: "POST", url: "/api/auth/wallet/challenge", payload: { walletAddress: "x", domain: "x", uri: "x", chain: "x" } }); assert.equal(response.statusCode, 503); await app.close(); });
test("test doubles expose durable-shaped quota and application operations", () => { const deps = createTestSecurityDependencies(); assert.equal(deps.quota.usage("app").remaining, 1000); for (let i = 0; i < 1000; i += 1) assert.equal(deps.quota.consume("app"), true); assert.equal(deps.quota.consume("app"), false); let called = false; const sink = { create: async () => { called = true; } }; assert.equal(typeof sink.create, "function"); assert.equal(called, false); });
