import type { FastifyInstance, FastifyReply, FastifyRequest } from "fastify";
import { randomUUID } from "node:crypto";
import { authorizeExternal, apiClientAuth } from "./api-access-boundary.js";
import type { ApiClientAuth } from "./api-client-auth.js";
import { createPrismaWalletAuth, createWalletAuth } from "./wallet-auth.js";
import { createPrismaWalletAuthStore } from "./wallet-auth-store.js";
import { createWebSessionManager } from "./web-session.js";
import { createPrismaApiClientAuth } from "./api-client-auth.js";
import { GENERIC_ERROR, MAX_APPLICATIONS, isPublicScope, scopeForRoute, type ExternalScope, type SafeApplication } from "./free-access-contract.js";
import { createPersistentSecurityAuditSink, createSecurityAuditSink, type AuditSink } from "./security-audit.js";
type Application = SafeApplication & { owner: string };
export type ApplicationRepository = { list(owner: string): Application[]; get(id: string): Application | undefined; create(value: Application): Application; disable(id: string): Application | undefined };
export type QuotaRepository = { usage(applicationId: string): { dailyQuota: number; used: number; remaining: number }; consume(applicationId: string): boolean };
export type SecurityRouteDeps = { available: boolean; wallet: any; sessions: any; applications: any; apiAuth: any; quota: any; audit: AuditSink };
// @ts-ignore test-double lambdas intentionally use the concrete map shapes above
export function createTestSecurityDependencies(): SecurityRouteDeps { const rows = new Map<string, Application>(); const quotaRows = new Map<string, { used: number; day: string }>(); const wallet = createWalletAuth(); return { available: true, wallet, sessions: createWebSessionManager(wallet.store), applications: { list: owner => [...rows.values()].filter(a => a.owner === owner), get: id => rows.get(id), create: value => { rows.set(value.id, value); return value; }, disable: id => { const value = rows.get(id); if (value) value.disabled = true; return value; } }, apiAuth: apiClientAuth, quota: { usage: id => { const day = new Date().toISOString().slice(0, 10); const row = quotaRows.get(id); const used = row?.day === day ? row.used : 0; return { dailyQuota: 1000, used, remaining: Math.max(0, 1000 - used) }; }, consume: id => { const day = new Date().toISOString().slice(0, 10); const row = quotaRows.get(id); if (row?.day === day && row.used >= 1000) return false; quotaRows.set(id, { day, used: row?.day === day ? row.used + 1 : 1 }); return true; } }, audit: createSecurityAuditSink() }; }
export const createInMemoryTestSecurityDependencies = createTestSecurityDependencies;
export function createUnavailableSecurityDependencies(): SecurityRouteDeps { return { ...createTestSecurityDependencies(), available: false }; }
export function createPrismaSecurityDependencies(db: any): SecurityRouteDeps {
  const walletStore = createPrismaWalletAuthStore(db);
  const applications = {
    async list(owner: string) { const rows = await db.freeAccessApplication.findMany({ where: { wallet: { walletAddress: owner } } }); return rows.map((row: any) => ({ id: row.id, owner, name: row.name, scopes: [], disabled: row.status === "DISABLED", createdAt: row.createdAt.toISOString() })); },
    async get(id: string) { const row = await db.freeAccessApplication.findUnique({ where: { id }, include: { wallet: true } }); return row ? { id: row.id, owner: row.wallet.walletAddress, name: row.name, scopes: [], disabled: row.status === "DISABLED", createdAt: row.createdAt.toISOString() } : undefined; },
    async create(value: Application) { const row = await db.freeAccessApplication.create({ data: { id: value.id, wallet: { connectOrCreate: { where: { walletAddress: value.owner }, create: { walletAddress: value.owner } } }, name: value.name } }); return { ...value, id: row.id }; },
    async disable(id: string) { const row = await db.freeAccessApplication.update({ where: { id }, data: { status: "DISABLED" } }); return row ? { id: row.id, name: row.name, disabled: true } : undefined; }
  };
  const quota = {
    async usage(applicationId: string) { const quotaDay = new Date(); quotaDay.setUTCHours(0, 0, 0, 0); const row = await db.freeAccessQuota.findUnique({ where: { applicationId_quotaDay: { applicationId, quotaDay } } }); const used = row?.used ?? 0; const dailyQuota = row?.dailyLimit ?? 1000; return { dailyQuota, used, remaining: Math.max(0, dailyQuota - used) }; },
    async consume(applicationId: string) { const quotaDay = new Date(); quotaDay.setUTCHours(0, 0, 0, 0); const row = await db.freeAccessQuota.upsert({ where: { applicationId_quotaDay: { applicationId, quotaDay } }, create: { applicationId, quotaDay, dailyLimit: 1000, used: 0 }, update: {} }); const result = await db.freeAccessQuota.updateMany({ where: { id: row.id, used: { lt: row.dailyLimit } }, data: { used: { increment: 1 } } }); return result.count === 1; }
  };
  return { available: true, wallet: createPrismaWalletAuth(db), sessions: createWebSessionManager(walletStore as any), applications, apiAuth: createPrismaApiClientAuth(db), quota, audit: createPersistentSecurityAuditSink({ create: (input) => db.freeAccessAuditEvent.create({ data: input }) }) };
}
const cookieValue = (request: FastifyRequest, name: string) => (request.headers.cookie ?? "").split(";").map(v => v.trim()).find(v => v.startsWith(`${name}=`))?.slice(name.length + 1);
const sessionToken = (request: FastifyRequest) => cookieValue(request, "__Host-mp_session");
const originOk = (request: FastifyRequest) => { const expected = process.env.WEB_ORIGIN; const origin = request.headers.origin; const referer = request.headers.referer; return Boolean(expected && ((origin && origin === expected) || (referer && referer.startsWith(`${expected}/`)))); };
export function registerSecurityRoutes(app: FastifyInstance, deps: SecurityRouteDeps) {
  const reject = (reply: FastifyReply, status = 401) => reply.code(status).send(GENERIC_ERROR); const sessionFor = async (request: FastifyRequest) => { const token = sessionToken(request); return token ? deps.sessions.get(token) : undefined; }; const stateChangeAllowed = async (request: FastifyRequest, reply: FastifyReply) => { const session = await sessionFor(request); const csrf = request.headers["x-csrf-token"]; if (!session || typeof csrf !== "string" || !deps.sessions.verifyCsrf(session, csrf) || !originOk(request)) { reject(reply); return undefined; } return session; };
  app.addHook("preHandler", async (request, reply) => { if (!deps.available && (request.url.startsWith("/api/auth/") || request.url.startsWith("/api/developer/") || request.url.startsWith("/oauth/") || request.url.startsWith("/api/public/"))) { reply.code(503).send(GENERIC_ERROR); return; } if (request.url.startsWith("/api/public/")) { if (request.headers.authorization) { authorizeExternal(request, reply, undefined, deps.apiAuth, deps.quota); return; } const token = cookieValue(request, "__Host-mp_session"); const session = token ? await deps.sessions.get(token) : undefined; const scope = scopeForRoute(request.method, request.url.split("?")[0]); if (!session || !scope || !deps.quota.consume(`session:${session.walletAddress}`)) { reply.code(session && scope ? 429 : 401).header("retry-after", "60").send(GENERIC_ERROR); return; } } });
  app.post("/api/auth/wallet/challenge", async (request: any, reply) => { const b = request.body ?? {}; if (typeof b.walletAddress !== "string" || typeof b.domain !== "string" || typeof b.uri !== "string" || typeof b.chain !== "string") return reject(reply, 400); return await deps.wallet.issueChallenge(b.walletAddress, { domain: b.domain, uri: b.uri, chain: b.chain, requestId: request.id }); });
  app.post("/api/auth/wallet/verify", async (request: any, reply) => { const b = request.body ?? {}; if (!(await deps.wallet.verifyChallenge(b))) return reject(reply); const created = await deps.sessions.create(b.walletAddress); if (!created) return reject(reply, 429); reply.header("set-cookie", `__Host-mp_session=${created.token}; Secure; HttpOnly; Path=/; SameSite=Strict`); await deps.audit.append({ event: "session_created", actor: b.walletAddress, success: true, route: request.url }); return { authenticated: true, walletAddress: b.walletAddress, csrf: created.csrf, expiresAt: new Date(created.session.expiresAt).toISOString() }; });
  app.get("/api/auth/session", async (request, reply) => { const s = await sessionFor(request); if (!s) return reject(reply); return { authenticated: true, walletAddress: s.walletAddress, expiresAt: new Date(s.expiresAt).toISOString() }; });
  app.post("/api/auth/logout", async (request, reply) => { const s = await stateChangeAllowed(request, reply); const token = sessionToken(request); if (s && token) await deps.sessions.revoke(token); reply.header("set-cookie", "__Host-mp_session=; Max-Age=0; Secure; HttpOnly; Path=/; SameSite=Strict"); return { ok: true }; });
  app.post("/oauth/token", async (request: any, reply) => { const auth = request.headers.authorization; const pair = auth?.startsWith("Basic ") ? Buffer.from(auth.slice(6), "base64").toString().split(":") : [request.body?.client_id, request.body?.client_secret]; if (request.body?.grant_type !== "client_credentials" || typeof pair[0] !== "string" || typeof pair[1] !== "string") return reject(reply, 400); const token = await deps.apiAuth.issueToken(pair[0], pair[1], request.body?.scope); return token ?? reject(reply); });
  // @ts-ignore the route adapter accepts both synchronous test doubles and async Prisma repositories
  app.get("/api/developer/applications", async (request, reply) => { const s = await sessionFor(request); if (!s) return reject(reply); return { data: (await deps.applications.list(s.walletAddress)).map(({ id, name, scopes, disabled, createdAt }) => ({ id, name, scopes, disabled, createdAt })) }; });
  app.post("/api/developer/applications", async (request: any, reply) => { const s = await stateChangeAllowed(request, reply); if (!s) return; if ((await deps.applications.list(s.walletAddress)).length >= MAX_APPLICATIONS) return reject(reply, 429); const b = request.body ?? {}; const scopes = Array.isArray(b.scopes) && b.scopes.length ? b.scopes : ["matches:read"]; if (typeof b.name !== "string" || b.name.trim().length < 1 || b.name.length > 80 || !scopes.every(isPublicScope)) return reject(reply, 400); const value: Application = { id: randomUUID(), owner: s.walletAddress, name: b.name.trim(), scopes: scopes as ExternalScope[], disabled: false, createdAt: new Date().toISOString() }; await deps.applications.create(value); await deps.audit.append({ event: "application_created", actor: s.walletAddress, route: request.url, success: true, metadata: { applicationId: value.id } }); return { data: { id: value.id, name: value.name, scopes: value.scopes, disabled: false, createdAt: value.createdAt } }; });
  app.post("/api/developer/applications/:applicationId/credentials", async (request: any, reply) => { const s = await stateChangeAllowed(request, reply); const a = await deps.applications.get(request.params.applicationId); if (!s || !a || a.owner !== s.walletAddress || a.disabled) return reject(reply, 404); const c = await deps.apiAuth.createCredential(a.id, a.scopes); return c ? { data: c } : reject(reply, 429); });
  app.post("/api/developer/applications/:applicationId/credentials/:credentialId/revoke", async (request: any, reply) => { const s = await stateChangeAllowed(request, reply); const a = await deps.applications.get(request.params.applicationId); if (!s || !a || a.owner !== s.walletAddress) return reject(reply, 404); const c = deps.apiAuth.findCredential ? await deps.apiAuth.findCredential(request.params.credentialId) : [...deps.apiAuth.store.credentials.values()].find((x: any) => x.id === request.params.credentialId && x.applicationId === a.id); if (!c) return reject(reply, 404); await deps.apiAuth.revokeCredential(c.clientId); return { data: { revoked: true } }; });
  app.post("/api/developer/applications/:applicationId/disable", async (request: any, reply) => { const s = await stateChangeAllowed(request, reply); const a = deps.applications.get(request.params.applicationId); if (!s || !a || a.owner !== s.walletAddress) return reject(reply, 404); await deps.applications.disable(a.id); await deps.apiAuth.revokeApplication(a.id); return { data: { id: a.id, disabled: true } }; });
  app.get("/api/developer/applications/:applicationId/usage", async (request: any, reply) => { const s = await sessionFor(request); const a = await deps.applications.get(request.params.applicationId); if (!s || !a || a.owner !== s.walletAddress) return reject(reply, 404); return { data: { applicationId: a.id, ...(await deps.quota.usage(a.id)) } }; });
  return deps;
}
