import type { FastifyInstance } from "fastify";
import { randomUUID } from "node:crypto";
import { authorizeExternal, apiClientAuth } from "./api-access-boundary.js";
import { createWalletAuth } from "./wallet-auth.js";
import { createWebSessionManager } from "./web-session.js";
import { GENERIC_ERROR, MAX_APPLICATIONS, isPublicScope, type ExternalScope } from "./free-access-contract.js";
const wallet = createWalletAuth(); const sessions = createWebSessionManager(wallet.store); const apps = new Map<string, { id: string; owner: string; name: string; scopes: ExternalScope[]; disabled: boolean; createdAt: string }>();
function sessionFrom(request: any) { const value = request.cookies?.mp_session ?? request.headers["x-mp-session"]; return typeof value === "string" ? sessions.get(value) : undefined; }
export function registerSecurityRoutes(app: FastifyInstance) {
  app.post("/api/auth/wallet/challenge", async (request: any, reply) => { const walletAddress = request.body?.walletAddress; if (typeof walletAddress !== "string" || walletAddress.length < 20) return reply.code(400).send(GENERIC_ERROR); return wallet.issueChallenge(walletAddress); });
  app.post("/api/auth/wallet/verify", async (request: any, reply) => { const body = request.body ?? {}; if (!wallet.verifyChallenge(body)) return reply.code(401).send(GENERIC_ERROR); const created = sessions.create(body.walletAddress); if (!created) return reply.code(429).send(GENERIC_ERROR); reply.header("set-cookie", `mp_session=${created.token}; HttpOnly; SameSite=Lax; Path=/`); return { authenticated: true, walletAddress: body.walletAddress, csrf: created.csrf }; });
  app.post("/api/auth/logout", async (request: any, reply) => { const s = sessionFrom(request); if (s) sessions.revoke(request.cookies?.mp_session ?? request.headers["x-mp-session"]); reply.header("set-cookie", "mp_session=; Max-Age=0; HttpOnly; SameSite=Lax; Path=/"); return { ok: true }; });
  app.post("/oauth/token", async (request: any, reply) => { const auth = request.headers.authorization; const [clientId, clientSecret] = auth?.startsWith("Basic ") ? Buffer.from(auth.slice(6), "base64").toString().split(":") : [request.body?.client_id, request.body?.client_secret]; if (request.body?.grant_type !== "client_credentials") return reply.code(400).send(GENERIC_ERROR); const token = apiClientAuth.issueToken(clientId, clientSecret, request.body?.scope); return token ?? reply.code(401).send(GENERIC_ERROR); });
  app.get("/api/developer/applications", async (request: any, reply) => { const s = sessionFrom(request); if (!s) return reply.code(401).send(GENERIC_ERROR); return { data: [...apps.values()].filter(a => a.owner === s.walletAddress).map(({id,name,scopes,disabled,createdAt}) => ({id,name,scopes,disabled,createdAt})) }; });
  app.post("/api/developer/applications", async (request: any, reply) => { const s = sessionFrom(request); if (!s) return reply.code(401).send(GENERIC_ERROR); if ([...apps.values()].filter(a => a.owner === s.walletAddress).length >= MAX_APPLICATIONS) return reply.code(429).send(GENERIC_ERROR); const name = typeof request.body?.name === "string" ? request.body.name.slice(0,80) : "Untitled application"; const scopes = (Array.isArray(request.body?.scopes) ? request.body.scopes : ["matches:read"]).filter(isPublicScope) as ExternalScope[]; const id = randomUUID(); const value = {id, owner:s.walletAddress,name,scopes,disabled:false,createdAt:new Date().toISOString()}; apps.set(id,value); return { data: value }; });
  app.post("/api/developer/applications/:id/credentials", async (request: any, reply) => { const s = sessionFrom(request); const a = apps.get(request.params.id); if (!s || !a || a.owner !== s.walletAddress || a.disabled) return reply.code(404).send(GENERIC_ERROR); const credential = apiClientAuth.createCredential(a.id, a.scopes); return credential ? { data: credential } : reply.code(429).send(GENERIC_ERROR); });
  app.post("/api/developer/applications/:id/disable", async (request: any, reply) => { const s = sessionFrom(request); const a = apps.get(request.params.id); if (!s || !a || a.owner !== s.walletAddress) return reply.code(404).send(GENERIC_ERROR); a.disabled = true; return { data: { id: a.id, disabled: true } }; });
  app.addHook("preHandler", async (request, reply) => { if (request.url.startsWith("/api/internal/")) return; if (["/api/health","/api/auth/","/oauth/","/api/developer/"].some(p => request.url.startsWith(p))) return; authorizeExternal(request, reply); });
}
