import nacl from "tweetnacl";
import bs58 from "bs58";
import { randomSecret, sha256 } from "./security-crypto.js";
import { createWalletAuthStore, type WalletAuthStore } from "./wallet-auth-store.js";
export const CHALLENGE_TTL_MS = 300_000; export const MAX_CHALLENGE_ATTEMPTS = 3;
export function canonicalChallenge(input: { walletAddress: string; domain: string; uri: string; chain: string; nonce: string; issuedAt: number; expiresAt: number; requestId: string }) { return ["MatchPulse off-chain sign-in", `Domain: ${input.domain}`, `URI: ${input.uri}`, `Chain: ${input.chain}`, `Wallet: ${input.walletAddress}`, `Nonce: ${input.nonce}`, `Issued-At: ${new Date(input.issuedAt).toISOString()}`, `Expiration: ${new Date(input.expiresAt).toISOString()}`, `Request-ID: ${input.requestId}`].join("\n"); }
function canonicalAddress(publicKey: string) { try { return bs58.encode(Buffer.from(bs58.decode(publicKey))); } catch { return undefined; } }
export function createWalletAuth(store: WalletAuthStore = createWalletAuthStore()) { return {
  issueChallenge(walletAddress: string, context: { domain?: string; uri?: string; chain?: string; requestId?: string } = {}) { const issuedAt = Date.now(); const expiresAt = issuedAt + CHALLENGE_TTL_MS; const nonce = randomSecret(24); const id = randomSecret(18); const challenge = { walletAddress, domain: context.domain ?? "localhost", uri: context.uri ?? "/api/auth/wallet/verify", chain: context.chain ?? "solana:devnet", nonce, issuedAt, expiresAt, requestId: context.requestId ?? randomSecret(12) }; const message = canonicalChallenge(challenge); store.putChallenge({ ...challenge, id, hash: sha256(message), attempts: 0, consumed: false }); return { id, challengeId: id, message, expiresAt: new Date(expiresAt).toISOString(), requestId: challenge.requestId }; },
  verifyChallenge(input: { challengeId?: string; id?: string; walletAddress?: string; signature?: string; publicKey?: string }) { const challengeId = input.challengeId ?? input.id; if (!challengeId || !input.walletAddress || !input.signature || !input.publicKey) return false; const c = store.getChallenge(challengeId); if (!c || c.consumed || c.expiresAt <= Date.now() || c.attempts >= MAX_CHALLENGE_ATTEMPTS || c.walletAddress !== input.walletAddress) return false; const message = canonicalChallenge(c); let valid = false; try { const key = canonicalAddress(input.publicKey); const legacy = input.publicKey === c.walletAddress ? Buffer.from(input.publicKey, "base64url") : undefined; const publicBytes = key === c.walletAddress ? Buffer.from(bs58.decode(input.publicKey)) : legacy; valid = Boolean(publicBytes) && nacl.sign.detached.verify(new TextEncoder().encode(message), Buffer.from(input.signature, "base64url"), publicBytes!); } catch { valid = false; } if (!valid) { c.attempts += 1; store.updateChallenge(c); return false; } c.consumed = true; store.updateChallenge(c); return true; }, store
}; }
