export type Challenge = { id: string; walletAddress: string; domain: string; uri: string; chain: string; nonce: string; issuedAt: number; requestId: string; hash: string; expiresAt: number; attempts: number; consumed: boolean };
export type Session = { id: string; walletAddress: string; tokenHash: string; csrfHash: string; createdAt: number; lastSeenAt: number; expiresAt: number; revokedAt?: number };
export type ChallengeVerification = { challenge: Challenge; valid: boolean; consume: boolean };
export type WalletAuthStore = { challenges: Map<string, Challenge>; sessions: Map<string, Session>; putChallenge(c: Challenge): void; getChallenge(id: string): Challenge | undefined; updateChallenge(c: Challenge): void; recordInvalidAttempt(id: string): Challenge | undefined; verifyAndConsumeChallenge(id: string, verify: (challenge: Challenge) => boolean): ChallengeVerification | undefined; putSession(s: Session): void; getSession(tokenHash: string): Session | undefined; updateSession(s: Session): void; revokeSession(id: string): void; countSessions(wallet: string): number; };
export function createWalletAuthStore(): WalletAuthStore { const challenges = new Map<string, Challenge>(); const sessions = new Map<string, Session>(); return {
  challenges, sessions,
  putChallenge: c => challenges.set(c.id, c), getChallenge: id => challenges.get(id), updateChallenge: c => challenges.set(c.id, c),
  recordInvalidAttempt: id => { const c = challenges.get(id); if (!c || c.consumed || c.expiresAt <= Date.now() || c.attempts >= 3) return undefined; c.attempts += 1; challenges.set(id, c); return c; },
  verifyAndConsumeChallenge: (id, verify) => { const c = challenges.get(id); if (!c || c.consumed || c.expiresAt <= Date.now() || c.attempts >= 3) return undefined; const valid = verify(c); if (!valid) { c.attempts += 1; challenges.set(id, c); return { challenge: c, valid: false, consume: false }; } c.consumed = true; challenges.set(id, c); return { challenge: c, valid: true, consume: true }; },
  putSession: s => sessions.set(s.id, s), getSession: hash => [...sessions.values()].find(x => x.tokenHash === hash), updateSession: s => sessions.set(s.id, s), revokeSession: id => { const s = sessions.get(id); if (s) { s.revokedAt = Date.now(); sessions.set(id, s); } }, countSessions: wallet => [...sessions.values()].filter(s => s.walletAddress === wallet && !s.revokedAt && s.expiresAt > Date.now()).length
}; }
