export type OddsIntelligenceVersion = "odds-intelligence-v1";
export type NormalizedOddsMarketType = "match_result_1x2" | "double_chance" | "total_goals" | "both_teams_to_score" | "asian_handicap" | "next_goal" | "correct_score" | "unknown";
export type NormalizedOddsSelectionType = "home" | "draw" | "away" | "none" | "yes" | "no" | "over" | "under" | "other" | "unknown";
export type OddsValidationIssue = "fixture_mismatch" | "invalid_odds_value" | "invalid_timestamp" | "unknown_market" | "unknown_selection" | "duplicate_snapshot" | "out_of_order_snapshot" | "market_incomplete" | "selection_missing" | "stale_snapshot" | "single_provider" | "provider_disagreement" | "provider_outlier" | "abnormal_jump" | "event_inconsistency" | "insufficient_history";
export type OddsReliabilityLevel = "unavailable" | "invalid" | "unreliable" | "limited" | "reliable" | "high_confidence";
export type OddsComponentScores = { structural_validity:number; freshness:number; market_completeness:number; provider_quality:number; provider_consensus:number; dispersion_quality:number; movement_integrity:number; event_consistency:number; historical_support:number; overall_reliability:number };
export type OddsFairProbabilitySelection = { selection:NormalizedOddsSelectionType; line:number|null; fair_probability:number; consensus_probability:number; probability_change_1m:number|null; probability_change_5m:number|null; movement_velocity:number|null; movement_acceleration:number|null };
export type OddsMarketIntelligence = { market_key:string; market_type:NormalizedOddsMarketType; line:number|null; complete:boolean; usable:boolean; selection_count:number; provider_count:number; snapshot_count:number; overround:number|null; provider_dispersion:number|null; volatility_score:number; selections:OddsFairProbabilitySelection[]; component_scores:OddsComponentScores; reliability_level:OddsReliabilityLevel; reliability_score:number; recommended_model_weight:number; issues:OddsValidationIssue[]; limitations:string[]; latest_timestamp:string|null };
export type InternalOddsIntelligenceContext = { odds_intelligence_version:OddsIntelligenceVersion; assessment_id:string; fixture_id:string; generated_at:string; status:OddsReliabilityLevel; usable_for_model:boolean; overall_reliability_score:number; recommended_market_model_weight:number; market_count:number; usable_market_count:number; provider_count:number; snapshot_count:number; consensus_score:number; freshness_score:number; volatility_score:number; anomaly_score:number; primary_match_result_market:OddsMarketIntelligence|null; markets:OddsMarketIntelligence[]; issues:OddsValidationIssue[]; limitations:string[] };
export type PublicMarketReliabilityLevel = "unavailable" | "low" | "limited" | "good" | "strong";
export type PublicMarketMovement = { market_label:string; selection_label:string; direction:"up"|"down"|"stable"|"volatile"|"unknown"; strength:"low"|"medium"|"high"; summary:string };
export type PublicMarketIntelligence = { market_intelligence_version:"public-market-intelligence-v1"; fixture_id:string; generated_at:string; availability:"available"|"limited"|"unavailable"; reliability:PublicMarketReliabilityLevel; freshness:"fresh"|"aging"|"stale"|"unknown"; provider_coverage:"none"|"single"|"limited"|"broad"; provider_agreement:"unknown"|"weak"|"mixed"|"strong"; volatility:"none"|"low"|"medium"|"high"; market_count:number; usable_market_count:number; provider_count:number; notable_movements:PublicMarketMovement[]; summary:string; limitations:string[]; last_update:string|null; safety_note:string };

export const PUBLIC_MARKET_SAFETY_NOTE = "Market intelligence describes the quality and movement of available odds data. It is not a betting recommendation or wagering instruction.";
const forbidden = new Set(["recommended_bet","bet","wager","stake","payout","profit","expected_value","ev","edge","wallet","deposit","token","secret","api_key","stack","raw","raw_payload","provider_payload","source_payload","debug","debug_lineage","formula","model_weights","model_coefficients","private_provider_weights","anomaly_thresholds"]);
const publicForbidden = new Set(["recommended_model_weight","assigned_weight","fair_probability","consensus_probability","provider_quality","component_scores","odds_intelligence_reference","specialist_contributions","feature_reference"]);
const marketTypes = new Set(["match_result_1x2","double_chance","total_goals","both_teams_to_score","asian_handicap","next_goal","correct_score","unknown"]);
const selections = new Set(["home","draw","away","none","yes","no","over","under","other","unknown"]);
const issues = new Set(["fixture_mismatch","invalid_odds_value","invalid_timestamp","unknown_market","unknown_selection","duplicate_snapshot","out_of_order_snapshot","market_incomplete","selection_missing","stale_snapshot","single_provider","provider_disagreement","provider_outlier","abnormal_jump","event_inconsistency","insufficient_history"]);
const levels = new Set(["unavailable","invalid","unreliable","limited","reliable","high_confidence"]);
const finite=(x:unknown):x is number=>typeof x === "number"&&Number.isFinite(x); const bound=(x:unknown):x is number=>finite(x)&&x>=0&&x<=1; const iso=(x:unknown):x is string=>typeof x === "string"&&x.trim()!==""&&Number.isFinite(Date.parse(x));
function obj(x:unknown,n:string):Record<string,unknown>{if(x===null||typeof x!=="object"||Array.isArray(x))throw new TypeError(`${n} must be an object.`);return x as Record<string,unknown>;} function nonempty(x:unknown,n:string){if(typeof x!=="string"||x.trim()==="")throw new TypeError(`${n} must be non-empty.`);} function strs(x:unknown,n:string){if(!Array.isArray(x)||!x.every(v=>typeof v === "string"))throw new TypeError(`${n} must contain strings.`);} function scan(x:unknown, pub=false, seen=new Set<object>()):void{if(x===null||typeof x!=="object"||seen.has(x))return;seen.add(x);for(const[k,v]of Object.entries(x)){const key=k.toLowerCase();if(forbidden.has(key)||(pub&&publicForbidden.has(key)))throw new Error(`Forbidden structured field: ${k}`);scan(v,pub,seen);}}
function scoreMap(x:unknown,n:string){const v=obj(x,n);for(const[k,val]of Object.entries(v)){if(!bound(val))throw new RangeError(`${n}.${k} must be in 0..1.`);}}
function validateMarket(m:OddsMarketIntelligence){nonempty(m.market_key,"market_key");if(!marketTypes.has(m.market_type)||!levels.has(m.reliability_level))throw new Error("Invalid market enum.");if(m.line!==null&&!finite(m.line))throw new Error("Invalid market line.");for(const k of ["selection_count","provider_count","snapshot_count"] as const)if(!Number.isInteger(m[k])||m[k]<0)throw new RangeError(`Invalid ${k}.`);if(!bound(m.volatility_score)||!bound(m.reliability_score)||!bound(m.recommended_model_weight))throw new RangeError("Invalid market score.");if(m.overround!==null&&!finite(m.overround)||m.provider_dispersion!==null&&(!finite(m.provider_dispersion)||m.provider_dispersion<0))throw new RangeError("Invalid market dispersion/overround.");if(m.latest_timestamp!==null&&!iso(m.latest_timestamp))throw new Error("Invalid market timestamp.");scoreMap(m.component_scores,"component_scores");if(!Array.isArray(m.selections))throw new TypeError("selections must be an array.");const keys=new Set<string>();for(const s of m.selections){if(!selections.has(s.selection))throw new Error("Invalid selection.");if(s.line!==null&&!finite(s.line))throw new Error("Invalid selection line.");for(const k of ["fair_probability","consensus_probability"] as const)if(!bound(s[k]))throw new RangeError(`Invalid ${k}.`);for(const k of ["probability_change_1m","probability_change_5m","movement_velocity","movement_acceleration"] as const)if(s[k]!==null&&!finite(s[k]))throw new RangeError(`Invalid ${k}.`);const key=`${s.selection}:${s.line}`;if(keys.has(key))throw new Error("Duplicate selection and line.");keys.add(key);}if(!Array.isArray(m.issues)||!m.issues.every(i=>issues.has(i)))throw new Error("Invalid odds issue.");strs(m.limitations,"market limitations");}
export function assertInternalOddsIntelligenceValid(payload:unknown):void{const p=obj(payload,"Internal odds intelligence") as unknown as InternalOddsIntelligenceContext;if(p.odds_intelligence_version!=="odds-intelligence-v1")throw new Error("Invalid odds intelligence version.");nonempty(p.assessment_id,"assessment_id");nonempty(p.fixture_id,"fixture_id");if(!iso(p.generated_at)||!levels.has(p.status)||typeof p.usable_for_model!=="boolean")throw new Error("Invalid internal odds identity/status.");for(const k of ["overall_reliability_score","recommended_market_model_weight","consensus_score","freshness_score","volatility_score","anomaly_score"] as const)if(!bound(p[k]))throw new RangeError(`Invalid ${k}.`);for(const k of ["market_count","usable_market_count","provider_count","snapshot_count"] as const)if(!Number.isInteger(p[k])||p[k]<0)throw new RangeError(`Invalid ${k}.`);strs(p.issues,"issues");if(!p.issues.every(i=>issues.has(i)))throw new Error("Invalid odds issue.");strs(p.limitations,"limitations");if(!Array.isArray(p.markets))throw new TypeError("markets must be an array.");const keys=new Set<string>();for(const m of p.markets){validateMarket(m);if(keys.has(m.market_key))throw new Error("Duplicate market key.");keys.add(m.market_key);}if(p.primary_match_result_market!==null)validateMarket(p.primary_match_result_market);scan(p);}
export function buildInternalOddsIntelligenceContext(input:InternalOddsIntelligenceContext):InternalOddsIntelligenceContext{const copy=structuredClone(input);copy.issues=[...new Set(copy.issues)];copy.limitations=[...new Set(copy.limitations)];copy.markets=copy.markets.map(m=>({...m,issues:[...new Set(m.issues)],limitations:[...new Set(m.limitations)],selections:m.selections.map(s=>({...s}))}));if(copy.primary_match_result_market)copy.primary_match_result_market={...copy.primary_match_result_market,issues:[...new Set(copy.primary_match_result_market.issues)],limitations:[...new Set(copy.primary_match_result_market.limitations)],selections:copy.primary_match_result_market.selections.map(s=>({...s}))};assertInternalOddsIntelligenceValid(copy);return copy;}
export function assertPublicMarketIntelligenceSafe(payload:unknown):void{const p=obj(payload,"Public market intelligence") as unknown as PublicMarketIntelligence;if(p.market_intelligence_version!=="public-market-intelligence-v1")throw new Error("Invalid public market intelligence version.");nonempty(p.fixture_id,"fixture_id");if(!iso(p.generated_at)||(p.last_update!==null&&!iso(p.last_update)))throw new Error("Invalid public timestamp.");if(!["available","limited","unavailable"].includes(p.availability)||!["unavailable","low","limited","good","strong"].includes(p.reliability)||!["fresh","aging","stale","unknown"].includes(p.freshness)||!["none","single","limited","broad"].includes(p.provider_coverage)||!["unknown","weak","mixed","strong"].includes(p.provider_agreement)||!["none","low","medium","high"].includes(p.volatility))throw new Error("Invalid public market enum.");for(const k of ["market_count","usable_market_count","provider_count"] as const)if(!Number.isInteger(p[k])||p[k]<0)throw new RangeError(`Invalid ${k}.`);if(!Array.isArray(p.notable_movements))throw new TypeError("notable_movements must be an array.");for(const m of p.notable_movements){nonempty(m.market_label,"market_label");nonempty(m.selection_label,"selection_label");if(!["up","down","stable","volatile","unknown"].includes(m.direction)||!["low","medium","high"].includes(m.strength))throw new Error("Invalid movement enum.");nonempty(m.summary,"movement summary");}nonempty(p.summary,"summary");strs(p.limitations,"limitations");if(p.safety_note!==PUBLIC_MARKET_SAFETY_NOTE)throw new Error("Invalid public safety note.");scan(p,true);}
export function buildPublicMarketIntelligence(input:PublicMarketIntelligence):PublicMarketIntelligence{const copy=structuredClone(input);copy.limitations=[...new Set(copy.limitations)];copy.notable_movements=copy.notable_movements.map(m=>({...m}));assertPublicMarketIntelligenceSafe(copy);return copy;}
